basePath: /
host: 'dazzlepod.com:65000'
info:
  title: txprop21
  description: Get Bitcoin transaction propagation information for a new transaction.
  contact:
    email: ayeowch@gmail.com
    name: Addy Yeow
    url: https://bitnodes.21.co
  license:
    name: MIT LICENSE
    url: https://opensource.org/licenses/MIT
  version: '0.1'
  x-21-category: blockchain
  x-21-github-project-url: https://github.com/ayeowch/txprop21
  x-21-keywords:
  - bitcoin
  - network
  - transaction
  - propagation
  - tx
  - txprop21
  x-21-total-price:
    min: 100
    max: 10000
  x-21-quick-buy: |
    $ 21 buy http://dazzlepod.com:65000/
    {
        "hash": "91d9f10971ab338d71e4a0a46fb105e0253256cada1a56b77b1515a46119bd39",
        "propagation": {
            "first_node": {
                "address": "123.56.188.103",
                "port": 8433
            },
            "last_node": {
                "address": "87.70.28.87",
                "port": 8333
            },
            "nodes": {
                "25%": 695,
                "50%": 3413,
                "75%": 6804,
                "count": 2047,
                "max": 1817882,
                "mean": 6872,
                "min": 2,
                "std": 48591
            },
            "propagation_level": 39.18
        },
        "reachable_nodes": 5224,
        "timestamp": 1483067888921
    }

    You spent: 5000 satoshis. Remaining 21.co balance: 1778789 satoshis.

    $ 21 buy http://dazzlepod.com:65000/?tx=91d9f1
    {
        "hash": "91d9f10971ab338d71e4a0a46fb105e0253256cada1a56b77b1515a46119bd39",
        "propagation": {
            "first_node": {
                "address": "123.56.188.103",
                "port": 8433
            },
            "last_node": {
                "address": "87.70.28.87",
                "port": 8333
            },
            "nodes": {
                "25%": 695,
                "50%": 3413,
                "75%": 6804,
                "count": 2047,
                "max": 1817882,
                "mean": 6872,
                "min": 2,
                "std": 48591
            },
            "propagation_level": 39.18
        },
        "reachable_nodes": 5224,
        "timestamp": 1483067888921
    }

    You spent: 5000 satoshis. Remaining 21.co balance: 1778789 satoshis.

    $ 21 buy http://dazzlepod.com:65000/unconfirmed-txs?limit=3
    [
        {
            "hash": "d986861eb5f9a0546dcc02961fd64691763a11661ed16ad474e6be887d58fb7e",
            "propagation": {
                "first_node": {
                    "address": "192.203.228.71",
                    "port": 8333
                },
                "last_node": {
                    "address": "25ra65xcfslnqzrg.onion",
                    "port": 8333
                },
                "nodes": {
                    "25%": 1123,
                    "50%": 3462,
                    "75%": 6690,
                    "count": 1806,
                    "max": 19786,
                    "mean": 4601,
                    "min": 9,
                    "std": 4531
                },
                "propagation_level": 34.52
            },
            "reachable_nodes": 5231,
            "timestamp": 1483076663960
        },
        {
            "hash": "af536099d1ae5326160a5e691bbaef5772f853fdce884c5b4253d88a4fb00033",
            "propagation": {
                "first_node": {
                    "address": "2a01:4f8:172:3ec2::2",
                    "port": 8333
                },
                "last_node": {
                    "address": "2001:41d0:a:15b2::1",
                    "port": 8333
                },
                "nodes": {
                    "25%": 188,
                    "50%": 231,
                    "75%": 263,
                    "count": 13,
                    "max": 281,
                    "mean": 216,
                    "min": 88,
                    "std": 61
                },
                "propagation_level": 0.25
            },
            "reachable_nodes": 5231,
            "timestamp": 1483076686552
        },
        {
            "hash": "199a77236a39cfa6de9fde18c1b020c8eefe1ab2e31ad25e215dd15f02195d38",
            "propagation": {
                "first_node": {
                    "address": "2a01:7e00::f03c:91ff:fe26:8c87",
                    "port": 8333
                },
                "last_node": {
                    "address": "75.77.157.146",
                    "port": 8333
                },
                "nodes": {
                    "25%": 1006,
                    "50%": 3357,
                    "75%": 6726,
                    "count": 3322,
                    "max": 54511,
                    "mean": 5431,
                    "min": 54,
                    "std": 6780
                },
                "propagation_level": 63.51
            },
            "reachable_nodes": 5231,
            "timestamp": 1483076631381
        }
    ]

    You spent: 300 satoshis. Remaining 21.co balance: 1778789 satoshis.
schemes: [http]
swagger: '2.0'
x-21-manifest-path: /manifest
